/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoginResultType } from './LoginResultType';
import {
    LoginResultTypeFromJSON,
    LoginResultTypeFromJSONTyped,
    LoginResultTypeToJSON,
} from './LoginResultType';

/**
 * 
 * @export
 * @interface AbpLoginResult
 */
export interface AbpLoginResult {
    /**
     * 
     * @type {LoginResultType}
     * @memberof AbpLoginResult
     */
    result?: LoginResultType;
    /**
     * 
     * @type {string}
     * @memberof AbpLoginResult
     */
    readonly description?: string | null;
}

/**
 * Check if a given object implements the AbpLoginResult interface.
 */
export function instanceOfAbpLoginResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AbpLoginResultFromJSON(json: any): AbpLoginResult {
    return AbpLoginResultFromJSONTyped(json, false);
}

export function AbpLoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbpLoginResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : LoginResultTypeFromJSON(json['result']),
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AbpLoginResultToJSON(value?: AbpLoginResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': LoginResultTypeToJSON(value.result),
    };
}

