/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationAuthConfigurationDto
 */
export interface ApplicationAuthConfigurationDto {
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof ApplicationAuthConfigurationDto
     */
    grantedPolicies?: { [key: string]: boolean; } | null;
}

/**
 * Check if a given object implements the ApplicationAuthConfigurationDto interface.
 */
export function instanceOfApplicationAuthConfigurationDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApplicationAuthConfigurationDtoFromJSON(json: any): ApplicationAuthConfigurationDto {
    return ApplicationAuthConfigurationDtoFromJSONTyped(json, false);
}

export function ApplicationAuthConfigurationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationAuthConfigurationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grantedPolicies': !exists(json, 'grantedPolicies') ? undefined : json['grantedPolicies'],
    };
}

export function ApplicationAuthConfigurationDtoToJSON(value?: ApplicationAuthConfigurationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grantedPolicies': value.grantedPolicies,
    };
}

