/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApplicationAuthConfigurationDto } from './ApplicationAuthConfigurationDto';
import {
    ApplicationAuthConfigurationDtoFromJSON,
    ApplicationAuthConfigurationDtoFromJSONTyped,
    ApplicationAuthConfigurationDtoToJSON,
} from './ApplicationAuthConfigurationDto';
import type { ApplicationFeatureConfigurationDto } from './ApplicationFeatureConfigurationDto';
import {
    ApplicationFeatureConfigurationDtoFromJSON,
    ApplicationFeatureConfigurationDtoFromJSONTyped,
    ApplicationFeatureConfigurationDtoToJSON,
} from './ApplicationFeatureConfigurationDto';
import type { ApplicationGlobalFeatureConfigurationDto } from './ApplicationGlobalFeatureConfigurationDto';
import {
    ApplicationGlobalFeatureConfigurationDtoFromJSON,
    ApplicationGlobalFeatureConfigurationDtoFromJSONTyped,
    ApplicationGlobalFeatureConfigurationDtoToJSON,
} from './ApplicationGlobalFeatureConfigurationDto';
import type { ApplicationLocalizationConfigurationDto } from './ApplicationLocalizationConfigurationDto';
import {
    ApplicationLocalizationConfigurationDtoFromJSON,
    ApplicationLocalizationConfigurationDtoFromJSONTyped,
    ApplicationLocalizationConfigurationDtoToJSON,
} from './ApplicationLocalizationConfigurationDto';
import type { ApplicationSettingConfigurationDto } from './ApplicationSettingConfigurationDto';
import {
    ApplicationSettingConfigurationDtoFromJSON,
    ApplicationSettingConfigurationDtoFromJSONTyped,
    ApplicationSettingConfigurationDtoToJSON,
} from './ApplicationSettingConfigurationDto';
import type { ClockDto } from './ClockDto';
import {
    ClockDtoFromJSON,
    ClockDtoFromJSONTyped,
    ClockDtoToJSON,
} from './ClockDto';
import type { CurrentTenantDto } from './CurrentTenantDto';
import {
    CurrentTenantDtoFromJSON,
    CurrentTenantDtoFromJSONTyped,
    CurrentTenantDtoToJSON,
} from './CurrentTenantDto';
import type { CurrentUserDto } from './CurrentUserDto';
import {
    CurrentUserDtoFromJSON,
    CurrentUserDtoFromJSONTyped,
    CurrentUserDtoToJSON,
} from './CurrentUserDto';
import type { MultiTenancyInfoDto } from './MultiTenancyInfoDto';
import {
    MultiTenancyInfoDtoFromJSON,
    MultiTenancyInfoDtoFromJSONTyped,
    MultiTenancyInfoDtoToJSON,
} from './MultiTenancyInfoDto';
import type { ObjectExtensionsDto } from './ObjectExtensionsDto';
import {
    ObjectExtensionsDtoFromJSON,
    ObjectExtensionsDtoFromJSONTyped,
    ObjectExtensionsDtoToJSON,
} from './ObjectExtensionsDto';
import type { TimingDto } from './TimingDto';
import {
    TimingDtoFromJSON,
    TimingDtoFromJSONTyped,
    TimingDtoToJSON,
} from './TimingDto';

/**
 * 
 * @export
 * @interface ApplicationConfigurationDto
 */
export interface ApplicationConfigurationDto {
    /**
     * 
     * @type {ApplicationLocalizationConfigurationDto}
     * @memberof ApplicationConfigurationDto
     */
    localization?: ApplicationLocalizationConfigurationDto;
    /**
     * 
     * @type {ApplicationAuthConfigurationDto}
     * @memberof ApplicationConfigurationDto
     */
    auth?: ApplicationAuthConfigurationDto;
    /**
     * 
     * @type {ApplicationSettingConfigurationDto}
     * @memberof ApplicationConfigurationDto
     */
    setting?: ApplicationSettingConfigurationDto;
    /**
     * 
     * @type {CurrentUserDto}
     * @memberof ApplicationConfigurationDto
     */
    currentUser?: CurrentUserDto;
    /**
     * 
     * @type {ApplicationFeatureConfigurationDto}
     * @memberof ApplicationConfigurationDto
     */
    features?: ApplicationFeatureConfigurationDto;
    /**
     * 
     * @type {ApplicationGlobalFeatureConfigurationDto}
     * @memberof ApplicationConfigurationDto
     */
    globalFeatures?: ApplicationGlobalFeatureConfigurationDto;
    /**
     * 
     * @type {MultiTenancyInfoDto}
     * @memberof ApplicationConfigurationDto
     */
    multiTenancy?: MultiTenancyInfoDto;
    /**
     * 
     * @type {CurrentTenantDto}
     * @memberof ApplicationConfigurationDto
     */
    currentTenant?: CurrentTenantDto;
    /**
     * 
     * @type {TimingDto}
     * @memberof ApplicationConfigurationDto
     */
    timing?: TimingDto;
    /**
     * 
     * @type {ClockDto}
     * @memberof ApplicationConfigurationDto
     */
    clock?: ClockDto;
    /**
     * 
     * @type {ObjectExtensionsDto}
     * @memberof ApplicationConfigurationDto
     */
    objectExtensions?: ObjectExtensionsDto;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ApplicationConfigurationDto
     */
    extraProperties?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ApplicationConfigurationDto interface.
 */
export function instanceOfApplicationConfigurationDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApplicationConfigurationDtoFromJSON(json: any): ApplicationConfigurationDto {
    return ApplicationConfigurationDtoFromJSONTyped(json, false);
}

export function ApplicationConfigurationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfigurationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localization': !exists(json, 'localization') ? undefined : ApplicationLocalizationConfigurationDtoFromJSON(json['localization']),
        'auth': !exists(json, 'auth') ? undefined : ApplicationAuthConfigurationDtoFromJSON(json['auth']),
        'setting': !exists(json, 'setting') ? undefined : ApplicationSettingConfigurationDtoFromJSON(json['setting']),
        'currentUser': !exists(json, 'currentUser') ? undefined : CurrentUserDtoFromJSON(json['currentUser']),
        'features': !exists(json, 'features') ? undefined : ApplicationFeatureConfigurationDtoFromJSON(json['features']),
        'globalFeatures': !exists(json, 'globalFeatures') ? undefined : ApplicationGlobalFeatureConfigurationDtoFromJSON(json['globalFeatures']),
        'multiTenancy': !exists(json, 'multiTenancy') ? undefined : MultiTenancyInfoDtoFromJSON(json['multiTenancy']),
        'currentTenant': !exists(json, 'currentTenant') ? undefined : CurrentTenantDtoFromJSON(json['currentTenant']),
        'timing': !exists(json, 'timing') ? undefined : TimingDtoFromJSON(json['timing']),
        'clock': !exists(json, 'clock') ? undefined : ClockDtoFromJSON(json['clock']),
        'objectExtensions': !exists(json, 'objectExtensions') ? undefined : ObjectExtensionsDtoFromJSON(json['objectExtensions']),
        'extraProperties': !exists(json, 'extraProperties') ? undefined : json['extraProperties'],
    };
}

export function ApplicationConfigurationDtoToJSON(value?: ApplicationConfigurationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'localization': ApplicationLocalizationConfigurationDtoToJSON(value.localization),
        'auth': ApplicationAuthConfigurationDtoToJSON(value.auth),
        'setting': ApplicationSettingConfigurationDtoToJSON(value.setting),
        'currentUser': CurrentUserDtoToJSON(value.currentUser),
        'features': ApplicationFeatureConfigurationDtoToJSON(value.features),
        'globalFeatures': ApplicationGlobalFeatureConfigurationDtoToJSON(value.globalFeatures),
        'multiTenancy': MultiTenancyInfoDtoToJSON(value.multiTenancy),
        'currentTenant': CurrentTenantDtoToJSON(value.currentTenant),
        'timing': TimingDtoToJSON(value.timing),
        'clock': ClockDtoToJSON(value.clock),
        'objectExtensions': ObjectExtensionsDtoToJSON(value.objectExtensions),
        'extraProperties': value.extraProperties,
    };
}

