/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationSettingConfigurationDto
 */
export interface ApplicationSettingConfigurationDto {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationSettingConfigurationDto
     */
    values?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ApplicationSettingConfigurationDto interface.
 */
export function instanceOfApplicationSettingConfigurationDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApplicationSettingConfigurationDtoFromJSON(json: any): ApplicationSettingConfigurationDto {
    return ApplicationSettingConfigurationDtoFromJSONTyped(json, false);
}

export function ApplicationSettingConfigurationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationSettingConfigurationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'values': !exists(json, 'values') ? undefined : json['values'],
    };
}

export function ApplicationSettingConfigurationDtoToJSON(value?: ApplicationSettingConfigurationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'values': value.values,
    };
}

