/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationGlobalFeatureConfigurationDto
 */
export interface ApplicationGlobalFeatureConfigurationDto {
    /**
     * 
     * @type {Set<string>}
     * @memberof ApplicationGlobalFeatureConfigurationDto
     */
    enabledFeatures?: Set<string> | null;
}

/**
 * Check if a given object implements the ApplicationGlobalFeatureConfigurationDto interface.
 */
export function instanceOfApplicationGlobalFeatureConfigurationDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApplicationGlobalFeatureConfigurationDtoFromJSON(json: any): ApplicationGlobalFeatureConfigurationDto {
    return ApplicationGlobalFeatureConfigurationDtoFromJSONTyped(json, false);
}

export function ApplicationGlobalFeatureConfigurationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationGlobalFeatureConfigurationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabledFeatures': !exists(json, 'enabledFeatures') ? undefined : json['enabledFeatures'],
    };
}

export function ApplicationGlobalFeatureConfigurationDtoToJSON(value?: ApplicationGlobalFeatureConfigurationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabledFeatures': value.enabledFeatures === undefined ? undefined : value.enabledFeatures === null ? null : Array.from(value.enabledFeatures as Set<any>),
    };
}

