/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordInput
 */
export interface ChangePasswordInput {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordInput
     */
    currentPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordInput
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ChangePasswordInput interface.
 */
export function instanceOfChangePasswordInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newPassword" in value;

    return isInstance;
}

export function ChangePasswordInputFromJSON(json: any): ChangePasswordInput {
    return ChangePasswordInputFromJSONTyped(json, false);
}

export function ChangePasswordInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPassword': !exists(json, 'currentPassword') ? undefined : json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function ChangePasswordInputToJSON(value?: ChangePasswordInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentPassword': value.currentPassword,
        'newPassword': value.newPassword,
    };
}

