/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClockDto
 */
export interface ClockDto {
    /**
     * 
     * @type {string}
     * @memberof ClockDto
     */
    kind?: string | null;
}

/**
 * Check if a given object implements the ClockDto interface.
 */
export function instanceOfClockDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClockDtoFromJSON(json: any): ClockDto {
    return ClockDtoFromJSONTyped(json, false);
}

export function ClockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClockDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
    };
}

export function ClockDtoToJSON(value?: ClockDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
    };
}

