/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtensionPropertyUiFormDto
 */
export interface ExtensionPropertyUiFormDto {
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionPropertyUiFormDto
     */
    isVisible?: boolean;
}

/**
 * Check if a given object implements the ExtensionPropertyUiFormDto interface.
 */
export function instanceOfExtensionPropertyUiFormDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExtensionPropertyUiFormDtoFromJSON(json: any): ExtensionPropertyUiFormDto {
    return ExtensionPropertyUiFormDtoFromJSONTyped(json, false);
}

export function ExtensionPropertyUiFormDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionPropertyUiFormDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isVisible': !exists(json, 'isVisible') ? undefined : json['isVisible'],
    };
}

export function ExtensionPropertyUiFormDtoToJSON(value?: ExtensionPropertyUiFormDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isVisible': value.isVisible,
    };
}

