/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtensionPropertyApiGetDto
 */
export interface ExtensionPropertyApiGetDto {
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionPropertyApiGetDto
     */
    isAvailable?: boolean;
}

/**
 * Check if a given object implements the ExtensionPropertyApiGetDto interface.
 */
export function instanceOfExtensionPropertyApiGetDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExtensionPropertyApiGetDtoFromJSON(json: any): ExtensionPropertyApiGetDto {
    return ExtensionPropertyApiGetDtoFromJSONTyped(json, false);
}

export function ExtensionPropertyApiGetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionPropertyApiGetDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAvailable': !exists(json, 'isAvailable') ? undefined : json['isAvailable'],
    };
}

export function ExtensionPropertyApiGetDtoToJSON(value?: ExtensionPropertyApiGetDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isAvailable': value.isAvailable,
    };
}

