/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureProviderDto
 */
export interface FeatureProviderDto {
    /**
     * 
     * @type {string}
     * @memberof FeatureProviderDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeatureProviderDto
     */
    key?: string | null;
}

/**
 * Check if a given object implements the FeatureProviderDto interface.
 */
export function instanceOfFeatureProviderDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeatureProviderDtoFromJSON(json: any): FeatureProviderDto {
    return FeatureProviderDtoFromJSONTyped(json, false);
}

export function FeatureProviderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureProviderDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function FeatureProviderDtoToJSON(value?: FeatureProviderDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'key': value.key,
    };
}

