/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeatureDto } from './FeatureDto';
import {
    FeatureDtoFromJSON,
    FeatureDtoFromJSONTyped,
    FeatureDtoToJSON,
} from './FeatureDto';

/**
 * 
 * @export
 * @interface FeatureGroupDto
 */
export interface FeatureGroupDto {
    /**
     * 
     * @type {string}
     * @memberof FeatureGroupDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeatureGroupDto
     */
    displayName?: string | null;
    /**
     * 
     * @type {Array<FeatureDto>}
     * @memberof FeatureGroupDto
     */
    features?: Array<FeatureDto> | null;
}

/**
 * Check if a given object implements the FeatureGroupDto interface.
 */
export function instanceOfFeatureGroupDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeatureGroupDtoFromJSON(json: any): FeatureGroupDto {
    return FeatureGroupDtoFromJSONTyped(json, false);
}

export function FeatureGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureGroupDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'features': !exists(json, 'features') ? undefined : (json['features'] === null ? null : (json['features'] as Array<any>).map(FeatureDtoFromJSON)),
    };
}

export function FeatureGroupDtoToJSON(value?: FeatureGroupDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'displayName': value.displayName,
        'features': value.features === undefined ? undefined : (value.features === null ? null : (value.features as Array<any>).map(FeatureDtoToJSON)),
    };
}

