/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindTenantResultDto
 */
export interface FindTenantResultDto {
    /**
     * 
     * @type {boolean}
     * @memberof FindTenantResultDto
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FindTenantResultDto
     */
    tenantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindTenantResultDto
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FindTenantResultDto
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the FindTenantResultDto interface.
 */
export function instanceOfFindTenantResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FindTenantResultDtoFromJSON(json: any): FindTenantResultDto {
    return FindTenantResultDtoFromJSONTyped(json, false);
}

export function FindTenantResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindTenantResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'tenantId': !exists(json, 'tenantId') ? undefined : json['tenantId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
    };
}

export function FindTenantResultDtoToJSON(value?: FindTenantResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'tenantId': value.tenantId,
        'name': value.name,
        'isActive': value.isActive,
    };
}

