/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeatureGroupDto } from './FeatureGroupDto';
import {
    FeatureGroupDtoFromJSON,
    FeatureGroupDtoFromJSONTyped,
    FeatureGroupDtoToJSON,
} from './FeatureGroupDto';

/**
 * 
 * @export
 * @interface GetFeatureListResultDto
 */
export interface GetFeatureListResultDto {
    /**
     * 
     * @type {Array<FeatureGroupDto>}
     * @memberof GetFeatureListResultDto
     */
    groups?: Array<FeatureGroupDto> | null;
}

/**
 * Check if a given object implements the GetFeatureListResultDto interface.
 */
export function instanceOfGetFeatureListResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFeatureListResultDtoFromJSON(json: any): GetFeatureListResultDto {
    return GetFeatureListResultDtoFromJSONTyped(json, false);
}

export function GetFeatureListResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFeatureListResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groups': !exists(json, 'groups') ? undefined : (json['groups'] === null ? null : (json['groups'] as Array<any>).map(FeatureGroupDtoFromJSON)),
    };
}

export function GetFeatureListResultDtoToJSON(value?: GetFeatureListResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groups': value.groups === undefined ? undefined : (value.groups === null ? null : (value.groups as Array<any>).map(FeatureGroupDtoToJSON)),
    };
}

