/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IanaTimeZone
 */
export interface IanaTimeZone {
    /**
     * 
     * @type {string}
     * @memberof IanaTimeZone
     */
    timeZoneName?: string | null;
}

/**
 * Check if a given object implements the IanaTimeZone interface.
 */
export function instanceOfIanaTimeZone(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IanaTimeZoneFromJSON(json: any): IanaTimeZone {
    return IanaTimeZoneFromJSONTyped(json, false);
}

export function IanaTimeZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): IanaTimeZone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeZoneName': !exists(json, 'timeZoneName') ? undefined : json['timeZoneName'],
    };
}

export function IanaTimeZoneToJSON(value?: IanaTimeZone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeZoneName': value.timeZoneName,
    };
}

