/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityUserUpdateRolesDto
 */
export interface IdentityUserUpdateRolesDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof IdentityUserUpdateRolesDto
     */
    roleNames: Array<string>;
}

/**
 * Check if a given object implements the IdentityUserUpdateRolesDto interface.
 */
export function instanceOfIdentityUserUpdateRolesDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "roleNames" in value;

    return isInstance;
}

export function IdentityUserUpdateRolesDtoFromJSON(json: any): IdentityUserUpdateRolesDto {
    return IdentityUserUpdateRolesDtoFromJSONTyped(json, false);
}

export function IdentityUserUpdateRolesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityUserUpdateRolesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleNames': json['roleNames'],
    };
}

export function IdentityUserUpdateRolesDtoToJSON(value?: IdentityUserUpdateRolesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roleNames': value.roleNames,
    };
}

