/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityUserUpdateDto
 */
export interface IdentityUserUpdateDto {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IdentityUserUpdateDto
     */
    readonly extraProperties?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUserUpdateDto
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityUserUpdateDto
     */
    lockoutEnabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof IdentityUserUpdateDto
     */
    roleNames?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityUserUpdateDto
     */
    concurrencyStamp?: string | null;
}

/**
 * Check if a given object implements the IdentityUserUpdateDto interface.
 */
export function instanceOfIdentityUserUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function IdentityUserUpdateDtoFromJSON(json: any): IdentityUserUpdateDto {
    return IdentityUserUpdateDtoFromJSONTyped(json, false);
}

export function IdentityUserUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityUserUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extraProperties': !exists(json, 'extraProperties') ? undefined : json['extraProperties'],
        'userName': json['userName'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'email': json['email'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'lockoutEnabled': !exists(json, 'lockoutEnabled') ? undefined : json['lockoutEnabled'],
        'roleNames': !exists(json, 'roleNames') ? undefined : json['roleNames'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
    };
}

export function IdentityUserUpdateDtoToJSON(value?: IdentityUserUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'name': value.name,
        'surname': value.surname,
        'email': value.email,
        'phoneNumber': value.phoneNumber,
        'isActive': value.isActive,
        'lockoutEnabled': value.lockoutEnabled,
        'roleNames': value.roleNames,
        'password': value.password,
        'concurrencyStamp': value.concurrencyStamp,
    };
}

