/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IdentityRoleDto } from './IdentityRoleDto';
import {
    IdentityRoleDtoFromJSON,
    IdentityRoleDtoFromJSONTyped,
    IdentityRoleDtoToJSON,
} from './IdentityRoleDto';

/**
 * 
 * @export
 * @interface IdentityRoleDtoListResultDto
 */
export interface IdentityRoleDtoListResultDto {
    /**
     * 
     * @type {Array<IdentityRoleDto>}
     * @memberof IdentityRoleDtoListResultDto
     */
    items?: Array<IdentityRoleDto> | null;
}

/**
 * Check if a given object implements the IdentityRoleDtoListResultDto interface.
 */
export function instanceOfIdentityRoleDtoListResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentityRoleDtoListResultDtoFromJSON(json: any): IdentityRoleDtoListResultDto {
    return IdentityRoleDtoListResultDtoFromJSONTyped(json, false);
}

export function IdentityRoleDtoListResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityRoleDtoListResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(IdentityRoleDtoFromJSON)),
    };
}

export function IdentityRoleDtoListResultDtoToJSON(value?: IdentityRoleDtoListResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(IdentityRoleDtoToJSON)),
    };
}

