/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentityRoleDto
 */
export interface IdentityRoleDto {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IdentityRoleDto
     */
    readonly extraProperties?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof IdentityRoleDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityRoleDto
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityRoleDto
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityRoleDto
     */
    isStatic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityRoleDto
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityRoleDto
     */
    concurrencyStamp?: string | null;
}

/**
 * Check if a given object implements the IdentityRoleDto interface.
 */
export function instanceOfIdentityRoleDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentityRoleDtoFromJSON(json: any): IdentityRoleDto {
    return IdentityRoleDtoFromJSONTyped(json, false);
}

export function IdentityRoleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityRoleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extraProperties': !exists(json, 'extraProperties') ? undefined : json['extraProperties'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isDefault': !exists(json, 'isDefault') ? undefined : json['isDefault'],
        'isStatic': !exists(json, 'isStatic') ? undefined : json['isStatic'],
        'isPublic': !exists(json, 'isPublic') ? undefined : json['isPublic'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
    };
}

export function IdentityRoleDtoToJSON(value?: IdentityRoleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'isDefault': value.isDefault,
        'isStatic': value.isStatic,
        'isPublic': value.isPublic,
        'concurrencyStamp': value.concurrencyStamp,
    };
}

