/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IValueValidator
 */
export interface IValueValidator {
    /**
     * 
     * @type {string}
     * @memberof IValueValidator
     */
    readonly name?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IValueValidator
     */
    readonly properties?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the IValueValidator interface.
 */
export function instanceOfIValueValidator(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IValueValidatorFromJSON(json: any): IValueValidator {
    return IValueValidatorFromJSONTyped(json, false);
}

export function IValueValidatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): IValueValidator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
    };
}

export function IValueValidatorToJSON(value?: IValueValidator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

