/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LanguageInfo
 */
export interface LanguageInfo {
    /**
     * 
     * @type {string}
     * @memberof LanguageInfo
     */
    cultureName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LanguageInfo
     */
    uiCultureName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LanguageInfo
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LanguageInfo
     */
    readonly twoLetterISOLanguageName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LanguageInfo
     */
    flagIcon?: string | null;
}

/**
 * Check if a given object implements the LanguageInfo interface.
 */
export function instanceOfLanguageInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LanguageInfoFromJSON(json: any): LanguageInfo {
    return LanguageInfoFromJSONTyped(json, false);
}

export function LanguageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguageInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cultureName': !exists(json, 'cultureName') ? undefined : json['cultureName'],
        'uiCultureName': !exists(json, 'uiCultureName') ? undefined : json['uiCultureName'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'twoLetterISOLanguageName': !exists(json, 'twoLetterISOLanguageName') ? undefined : json['twoLetterISOLanguageName'],
        'flagIcon': !exists(json, 'flagIcon') ? undefined : json['flagIcon'],
    };
}

export function LanguageInfoToJSON(value?: LanguageInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cultureName': value.cultureName,
        'uiCultureName': value.uiCultureName,
        'displayName': value.displayName,
        'flagIcon': value.flagIcon,
    };
}

