/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalizableStringDto
 */
export interface LocalizableStringDto {
    /**
     * 
     * @type {string}
     * @memberof LocalizableStringDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalizableStringDto
     */
    resource?: string | null;
}

/**
 * Check if a given object implements the LocalizableStringDto interface.
 */
export function instanceOfLocalizableStringDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocalizableStringDtoFromJSON(json: any): LocalizableStringDto {
    return LocalizableStringDtoFromJSONTyped(json, false);
}

export function LocalizableStringDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizableStringDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'resource': !exists(json, 'resource') ? undefined : json['resource'],
    };
}

export function LocalizableStringDtoToJSON(value?: LocalizableStringDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'resource': value.resource,
    };
}

