/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LoginResultType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type LoginResultType = typeof LoginResultType[keyof typeof LoginResultType];


export function LoginResultTypeFromJSON(json: any): LoginResultType {
    return LoginResultTypeFromJSONTyped(json, false);
}

export function LoginResultTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResultType {
    return json as LoginResultType;
}

export function LoginResultTypeToJSON(value?: LoginResultType | null): any {
    return value as any;
}

