/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFileDto } from './MediaFileDto';
import {
    MediaFileDtoFromJSON,
    MediaFileDtoFromJSONTyped,
    MediaFileDtoToJSON,
} from './MediaFileDto';

/**
 * 
 * @export
 * @interface MediaFileDtoPagedResultDto
 */
export interface MediaFileDtoPagedResultDto {
    /**
     * 
     * @type {Array<MediaFileDto>}
     * @memberof MediaFileDtoPagedResultDto
     */
    items?: Array<MediaFileDto> | null;
    /**
     * 
     * @type {number}
     * @memberof MediaFileDtoPagedResultDto
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the MediaFileDtoPagedResultDto interface.
 */
export function instanceOfMediaFileDtoPagedResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaFileDtoPagedResultDtoFromJSON(json: any): MediaFileDtoPagedResultDto {
    return MediaFileDtoPagedResultDtoFromJSONTyped(json, false);
}

export function MediaFileDtoPagedResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaFileDtoPagedResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(MediaFileDtoFromJSON)),
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
    };
}

export function MediaFileDtoPagedResultDtoToJSON(value?: MediaFileDtoPagedResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(MediaFileDtoToJSON)),
        'totalCount': value.totalCount,
    };
}

