/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiTenancyInfoDto
 */
export interface MultiTenancyInfoDto {
    /**
     * 
     * @type {boolean}
     * @memberof MultiTenancyInfoDto
     */
    isEnabled?: boolean;
}

/**
 * Check if a given object implements the MultiTenancyInfoDto interface.
 */
export function instanceOfMultiTenancyInfoDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MultiTenancyInfoDtoFromJSON(json: any): MultiTenancyInfoDto {
    return MultiTenancyInfoDtoFromJSONTyped(json, false);
}

export function MultiTenancyInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiTenancyInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isEnabled': !exists(json, 'isEnabled') ? undefined : json['isEnabled'],
    };
}

export function MultiTenancyInfoDtoToJSON(value?: MultiTenancyInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isEnabled': value.isEnabled,
    };
}

