/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameValue
 */
export interface NameValue {
    /**
     * 
     * @type {string}
     * @memberof NameValue
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameValue
     */
    value?: string | null;
}

/**
 * Check if a given object implements the NameValue interface.
 */
export function instanceOfNameValue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NameValueFromJSON(json: any): NameValue {
    return NameValueFromJSONTyped(json, false);
}

export function NameValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function NameValueToJSON(value?: NameValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

