/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParameterApiDescriptionModel
 */
export interface ParameterApiDescriptionModel {
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    nameOnMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    jsonName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    typeSimple?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ParameterApiDescriptionModel
     */
    isOptional?: boolean;
    /**
     * 
     * @type {any}
     * @memberof ParameterApiDescriptionModel
     */
    defaultValue?: any | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ParameterApiDescriptionModel
     */
    constraintTypes?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    bindingSourceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ParameterApiDescriptionModel
     */
    descriptorName?: string | null;
}

/**
 * Check if a given object implements the ParameterApiDescriptionModel interface.
 */
export function instanceOfParameterApiDescriptionModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ParameterApiDescriptionModelFromJSON(json: any): ParameterApiDescriptionModel {
    return ParameterApiDescriptionModelFromJSONTyped(json, false);
}

export function ParameterApiDescriptionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterApiDescriptionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nameOnMethod': !exists(json, 'nameOnMethod') ? undefined : json['nameOnMethod'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'jsonName': !exists(json, 'jsonName') ? undefined : json['jsonName'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'typeSimple': !exists(json, 'typeSimple') ? undefined : json['typeSimple'],
        'isOptional': !exists(json, 'isOptional') ? undefined : json['isOptional'],
        'defaultValue': !exists(json, 'defaultValue') ? undefined : json['defaultValue'],
        'constraintTypes': !exists(json, 'constraintTypes') ? undefined : json['constraintTypes'],
        'bindingSourceId': !exists(json, 'bindingSourceId') ? undefined : json['bindingSourceId'],
        'descriptorName': !exists(json, 'descriptorName') ? undefined : json['descriptorName'],
    };
}

export function ParameterApiDescriptionModelToJSON(value?: ParameterApiDescriptionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nameOnMethod': value.nameOnMethod,
        'name': value.name,
        'jsonName': value.jsonName,
        'type': value.type,
        'typeSimple': value.typeSimple,
        'isOptional': value.isOptional,
        'defaultValue': value.defaultValue,
        'constraintTypes': value.constraintTypes,
        'bindingSourceId': value.bindingSourceId,
        'descriptorName': value.descriptorName,
    };
}

