/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProviderInfoDto } from './ProviderInfoDto';
import {
    ProviderInfoDtoFromJSON,
    ProviderInfoDtoFromJSONTyped,
    ProviderInfoDtoToJSON,
} from './ProviderInfoDto';

/**
 * 
 * @export
 * @interface PermissionGrantInfoDto
 */
export interface PermissionGrantInfoDto {
    /**
     * 
     * @type {string}
     * @memberof PermissionGrantInfoDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PermissionGrantInfoDto
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PermissionGrantInfoDto
     */
    parentName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PermissionGrantInfoDto
     */
    isGranted?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionGrantInfoDto
     */
    allowedProviders?: Array<string> | null;
    /**
     * 
     * @type {Array<ProviderInfoDto>}
     * @memberof PermissionGrantInfoDto
     */
    grantedProviders?: Array<ProviderInfoDto> | null;
}

/**
 * Check if a given object implements the PermissionGrantInfoDto interface.
 */
export function instanceOfPermissionGrantInfoDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PermissionGrantInfoDtoFromJSON(json: any): PermissionGrantInfoDto {
    return PermissionGrantInfoDtoFromJSONTyped(json, false);
}

export function PermissionGrantInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionGrantInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'parentName': !exists(json, 'parentName') ? undefined : json['parentName'],
        'isGranted': !exists(json, 'isGranted') ? undefined : json['isGranted'],
        'allowedProviders': !exists(json, 'allowedProviders') ? undefined : json['allowedProviders'],
        'grantedProviders': !exists(json, 'grantedProviders') ? undefined : (json['grantedProviders'] === null ? null : (json['grantedProviders'] as Array<any>).map(ProviderInfoDtoFromJSON)),
    };
}

export function PermissionGrantInfoDtoToJSON(value?: PermissionGrantInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'displayName': value.displayName,
        'parentName': value.parentName,
        'isGranted': value.isGranted,
        'allowedProviders': value.allowedProviders,
        'grantedProviders': value.grantedProviders === undefined ? undefined : (value.grantedProviders === null ? null : (value.grantedProviders as Array<any>).map(ProviderInfoDtoToJSON)),
    };
}

