/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileDto
 */
export interface ProfileDto {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProfileDto
     */
    readonly extraProperties?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileDto
     */
    isExternal?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileDto
     */
    hasPassword?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    concurrencyStamp?: string | null;
}

/**
 * Check if a given object implements the ProfileDto interface.
 */
export function instanceOfProfileDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileDtoFromJSON(json: any): ProfileDto {
    return ProfileDtoFromJSONTyped(json, false);
}

export function ProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extraProperties': !exists(json, 'extraProperties') ? undefined : json['extraProperties'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'isExternal': !exists(json, 'isExternal') ? undefined : json['isExternal'],
        'hasPassword': !exists(json, 'hasPassword') ? undefined : json['hasPassword'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
    };
}

export function ProfileDtoToJSON(value?: ProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'email': value.email,
        'name': value.name,
        'surname': value.surname,
        'phoneNumber': value.phoneNumber,
        'isExternal': value.isExternal,
        'hasPassword': value.hasPassword,
        'concurrencyStamp': value.concurrencyStamp,
    };
}

