/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderInfoDto
 */
export interface ProviderInfoDto {
    /**
     * 
     * @type {string}
     * @memberof ProviderInfoDto
     */
    providerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfoDto
     */
    providerKey?: string | null;
}

/**
 * Check if a given object implements the ProviderInfoDto interface.
 */
export function instanceOfProviderInfoDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProviderInfoDtoFromJSON(json: any): ProviderInfoDto {
    return ProviderInfoDtoFromJSONTyped(json, false);
}

export function ProviderInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'providerName': !exists(json, 'providerName') ? undefined : json['providerName'],
        'providerKey': !exists(json, 'providerKey') ? undefined : json['providerKey'],
    };
}

export function ProviderInfoDtoToJSON(value?: ProviderInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'providerName': value.providerName,
        'providerKey': value.providerKey,
    };
}

