/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RemoteServiceErrorInfo } from './RemoteServiceErrorInfo';
import {
    RemoteServiceErrorInfoFromJSON,
    RemoteServiceErrorInfoFromJSONTyped,
    RemoteServiceErrorInfoToJSON,
} from './RemoteServiceErrorInfo';

/**
 * 
 * @export
 * @interface RemoteServiceErrorResponse
 */
export interface RemoteServiceErrorResponse {
    /**
     * 
     * @type {RemoteServiceErrorInfo}
     * @memberof RemoteServiceErrorResponse
     */
    error?: RemoteServiceErrorInfo;
}

/**
 * Check if a given object implements the RemoteServiceErrorResponse interface.
 */
export function instanceOfRemoteServiceErrorResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RemoteServiceErrorResponseFromJSON(json: any): RemoteServiceErrorResponse {
    return RemoteServiceErrorResponseFromJSONTyped(json, false);
}

export function RemoteServiceErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteServiceErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : RemoteServiceErrorInfoFromJSON(json['error']),
    };
}

export function RemoteServiceErrorResponseToJSON(value?: RemoteServiceErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': RemoteServiceErrorInfoToJSON(value.error),
    };
}

