/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteServiceValidationErrorInfo
 */
export interface RemoteServiceValidationErrorInfo {
    /**
     * 
     * @type {string}
     * @memberof RemoteServiceValidationErrorInfo
     */
    message?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoteServiceValidationErrorInfo
     */
    members?: Array<string> | null;
}

/**
 * Check if a given object implements the RemoteServiceValidationErrorInfo interface.
 */
export function instanceOfRemoteServiceValidationErrorInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RemoteServiceValidationErrorInfoFromJSON(json: any): RemoteServiceValidationErrorInfo {
    return RemoteServiceValidationErrorInfoFromJSONTyped(json, false);
}

export function RemoteServiceValidationErrorInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteServiceValidationErrorInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'members': !exists(json, 'members') ? undefined : json['members'],
    };
}

export function RemoteServiceValidationErrorInfoToJSON(value?: RemoteServiceValidationErrorInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'members': value.members,
    };
}

