/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnValueApiDescriptionModel
 */
export interface ReturnValueApiDescriptionModel {
    /**
     * 
     * @type {string}
     * @memberof ReturnValueApiDescriptionModel
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReturnValueApiDescriptionModel
     */
    typeSimple?: string | null;
}

/**
 * Check if a given object implements the ReturnValueApiDescriptionModel interface.
 */
export function instanceOfReturnValueApiDescriptionModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReturnValueApiDescriptionModelFromJSON(json: any): ReturnValueApiDescriptionModel {
    return ReturnValueApiDescriptionModelFromJSONTyped(json, false);
}

export function ReturnValueApiDescriptionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnValueApiDescriptionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'typeSimple': !exists(json, 'typeSimple') ? undefined : json['typeSimple'],
    };
}

export function ReturnValueApiDescriptionModelToJSON(value?: ReturnValueApiDescriptionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'typeSimple': value.typeSimple,
    };
}

