/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendTestEmailInput
 */
export interface SendTestEmailInput {
    /**
     * 
     * @type {string}
     * @memberof SendTestEmailInput
     */
    senderEmailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof SendTestEmailInput
     */
    targetEmailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof SendTestEmailInput
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof SendTestEmailInput
     */
    body?: string | null;
}

/**
 * Check if a given object implements the SendTestEmailInput interface.
 */
export function instanceOfSendTestEmailInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "senderEmailAddress" in value;
    isInstance = isInstance && "targetEmailAddress" in value;
    isInstance = isInstance && "subject" in value;

    return isInstance;
}

export function SendTestEmailInputFromJSON(json: any): SendTestEmailInput {
    return SendTestEmailInputFromJSONTyped(json, false);
}

export function SendTestEmailInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendTestEmailInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'senderEmailAddress': json['senderEmailAddress'],
        'targetEmailAddress': json['targetEmailAddress'],
        'subject': json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function SendTestEmailInputToJSON(value?: SendTestEmailInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'senderEmailAddress': value.senderEmailAddress,
        'targetEmailAddress': value.targetEmailAddress,
        'subject': value.subject,
        'body': value.body,
    };
}

