/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantUpdateDto
 */
export interface TenantUpdateDto {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TenantUpdateDto
     */
    readonly extraProperties?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof TenantUpdateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TenantUpdateDto
     */
    concurrencyStamp?: string | null;
}

/**
 * Check if a given object implements the TenantUpdateDto interface.
 */
export function instanceOfTenantUpdateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TenantUpdateDtoFromJSON(json: any): TenantUpdateDto {
    return TenantUpdateDtoFromJSONTyped(json, false);
}

export function TenantUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extraProperties': !exists(json, 'extraProperties') ? undefined : json['extraProperties'],
        'name': json['name'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
    };
}

export function TenantUpdateDtoToJSON(value?: TenantUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'concurrencyStamp': value.concurrencyStamp,
    };
}

