/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TenantDto } from './TenantDto';
import {
    TenantDtoFromJSON,
    TenantDtoFromJSONTyped,
    TenantDtoToJSON,
} from './TenantDto';

/**
 * 
 * @export
 * @interface TenantDtoPagedResultDto
 */
export interface TenantDtoPagedResultDto {
    /**
     * 
     * @type {Array<TenantDto>}
     * @memberof TenantDtoPagedResultDto
     */
    items?: Array<TenantDto> | null;
    /**
     * 
     * @type {number}
     * @memberof TenantDtoPagedResultDto
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the TenantDtoPagedResultDto interface.
 */
export function instanceOfTenantDtoPagedResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TenantDtoPagedResultDtoFromJSON(json: any): TenantDtoPagedResultDto {
    return TenantDtoPagedResultDtoFromJSONTyped(json, false);
}

export function TenantDtoPagedResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDtoPagedResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(TenantDtoFromJSON)),
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
    };
}

export function TenantDtoPagedResultDtoToJSON(value?: TenantDtoPagedResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(TenantDtoToJSON)),
        'totalCount': value.totalCount,
    };
}

