/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TimeZone } from './TimeZone';
import {
    TimeZoneFromJSON,
    TimeZoneFromJSONTyped,
    TimeZoneToJSON,
} from './TimeZone';

/**
 * 
 * @export
 * @interface TimingDto
 */
export interface TimingDto {
    /**
     * 
     * @type {TimeZone}
     * @memberof TimingDto
     */
    timeZone?: TimeZone;
}

/**
 * Check if a given object implements the TimingDto interface.
 */
export function instanceOfTimingDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimingDtoFromJSON(json: any): TimingDto {
    return TimingDtoFromJSONTyped(json, false);
}

export function TimingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimingDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeZone': !exists(json, 'timeZone') ? undefined : TimeZoneFromJSON(json['timeZone']),
    };
}

export function TimingDtoToJSON(value?: TimingDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeZone': TimeZoneToJSON(value.timeZone),
    };
}

