/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePermissionDto
 */
export interface UpdatePermissionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePermissionDto
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePermissionDto
     */
    isGranted?: boolean;
}

/**
 * Check if a given object implements the UpdatePermissionDto interface.
 */
export function instanceOfUpdatePermissionDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePermissionDtoFromJSON(json: any): UpdatePermissionDto {
    return UpdatePermissionDtoFromJSONTyped(json, false);
}

export function UpdatePermissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePermissionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isGranted': !exists(json, 'isGranted') ? undefined : json['isGranted'],
    };
}

export function UpdatePermissionDtoToJSON(value?: UpdatePermissionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'isGranted': value.isGranted,
    };
}

