/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileDto
 */
export interface UpdateProfileDto {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateProfileDto
     */
    readonly extraProperties?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    surname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    concurrencyStamp?: string | null;
}

/**
 * Check if a given object implements the UpdateProfileDto interface.
 */
export function instanceOfUpdateProfileDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateProfileDtoFromJSON(json: any): UpdateProfileDto {
    return UpdateProfileDtoFromJSONTyped(json, false);
}

export function UpdateProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extraProperties': !exists(json, 'extraProperties') ? undefined : json['extraProperties'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'concurrencyStamp': !exists(json, 'concurrencyStamp') ? undefined : json['concurrencyStamp'],
    };
}

export function UpdateProfileDtoToJSON(value?: UpdateProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'email': value.email,
        'name': value.name,
        'surname': value.surname,
        'phoneNumber': value.phoneNumber,
        'concurrencyStamp': value.concurrencyStamp,
    };
}

