/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLoginInfo
 */
export interface UserLoginInfo {
    /**
     * 
     * @type {string}
     * @memberof UserLoginInfo
     */
    userNameOrEmailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginInfo
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserLoginInfo
     */
    rememberMe?: boolean;
}

/**
 * Check if a given object implements the UserLoginInfo interface.
 */
export function instanceOfUserLoginInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userNameOrEmailAddress" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UserLoginInfoFromJSON(json: any): UserLoginInfo {
    return UserLoginInfoFromJSONTyped(json, false);
}

export function UserLoginInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userNameOrEmailAddress': json['userNameOrEmailAddress'],
        'password': json['password'],
        'rememberMe': !exists(json, 'rememberMe') ? undefined : json['rememberMe'],
    };
}

export function UserLoginInfoToJSON(value?: UserLoginInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userNameOrEmailAddress': value.userNameOrEmailAddress,
        'password': value.password,
        'rememberMe': value.rememberMe,
    };
}

