/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';

/**
 * 
 * @export
 * @interface UserDataListResultDto
 */
export interface UserDataListResultDto {
    /**
     * 
     * @type {Array<UserData>}
     * @memberof UserDataListResultDto
     */
    items?: Array<UserData> | null;
}

/**
 * Check if a given object implements the UserDataListResultDto interface.
 */
export function instanceOfUserDataListResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDataListResultDtoFromJSON(json: any): UserDataListResultDto {
    return UserDataListResultDtoFromJSONTyped(json, false);
}

export function UserDataListResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDataListResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(UserDataFromJSON)),
    };
}

export function UserDataListResultDtoToJSON(value?: UserDataListResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(UserDataToJSON)),
    };
}

