/* tslint:disable */
/* eslint-disable */
/**
 * Gcv API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApplicationApiDescriptionModel,
  RemoteServiceErrorResponse,
} from '../models';

export interface ApiAbpApiDefinitionGetRequest {
    includeTypes?: boolean;
}

/**
 * 
 */
export class AbpApiDefinitionApi extends runtime.BaseAPI {

    /**
     */
    private apiAbpApiDefinitionGetRaw = async (requestParameters: ApiAbpApiDefinitionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApplicationApiDescriptionModel>> => {
        const queryParameters: any = {};

        if (requestParameters.includeTypes !== undefined) {
            queryParameters['IncludeTypes'] = requestParameters.includeTypes;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/abp/api-definition`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    public apiAbpApiDefinitionGet = async (requestParameters: ApiAbpApiDefinitionGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApplicationApiDescriptionModel> => {
        const response = await this.apiAbpApiDefinitionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
